//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoom3Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int C_Id { get; set; }
        public int C_US_Id { get; set; }
        public int C_PH_Id { get; set; }
    
        public virtual Photo Photo { get; set; }
    }
}
