//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoom3Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Photo = new HashSet<Photo>();
        }
    
        public int CAT_Id { get; set; }
        public string CAT_Description { get; set; }
    
        public virtual ICollection<Photo> Photo { get; set; }
    }
}
