//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoom3Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardType
    {
        public CreditCardType()
        {
            this.CreditCard = new HashSet<CreditCard>();
        }
    
        public int CT_Id { get; set; }
        public string CT_Type { get; set; }
    
        public virtual ICollection<CreditCard> CreditCard { get; set; }
    }
}
