//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoom3Web
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class CreditCard
    {
        public int CC_Id { get; set; }
        [RegularExpression("^[0-9]{16}$", ErrorMessage = "Número de tarjeta no válido")]
        public string CC_Number { get; set; }
        [RegularExpression("^[0-9]{3}$", ErrorMessage = "CVV no válido")]
        public Nullable<int> CC_CVV2 { get; set; }
        [StringLength(200, ErrorMessage = "Nombre incorrrecto", MinimumLength = 5)]
        public string CC_Name { get; set; }
        public Nullable<bool> CC_Primary { get; set; }
        public Nullable<bool> CC_SaveCard { get; set; }
        public Nullable<int> CC_CT_Id { get; set; }
        public int CC_U_Id { get; set; }
        public string CC_AccountNumber { get; set; }
        [RegularExpression("^([1-9]|1[012])$", ErrorMessage = "CVV no válido")]
        public Nullable<int> CC_ExpiredMonth { get; set; }
        [RegularExpression("^2[0-9]{3}$", ErrorMessage = "CVV no válido")]
        public Nullable<int> CC_ExpiredYear { get; set; }
    
        public virtual CreditCardType CreditCardType { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
