//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoom3Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Likes
    {
        public int LIK_Id { get; set; }
        public int LIK_US_Id { get; set; }
        public int LIK_PH_Id { get; set; }
        public bool LIK_ButtonLike { get; set; }
    }
}
