//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoom3Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NOT_Id { get; set; }
        public int NOT_U_Id { get; set; }
        public int NOT_NT_Id { get; set; }
        public int NOT_PH_Id { get; set; }
        public bool NOT_Leido { get; set; }
        public string NOT_Tittle { get; set; }
        public string NOT_Description { get; set; }
        public System.DateTime NOT_Date { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
