//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoom3Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Photo
    {
        public Photo()
        {
            this.Favourites = new HashSet<Favourites>();
            this.Notifications = new HashSet<Notifications>();
            this.Purchases = new HashSet<Purchases>();
            this.Cart = new HashSet<Cart>();
        }
    
        public int PH_Id { get; set; }
        [Required]
        public string PH_Title { get; set; }
        public string PH_Description { get; set; }
        public Nullable<decimal> PH_Price { get; set; }
        public int PH_Favourites { get; set; }
        public bool PH_InCart { get; set; }
        public int PH_CAT_Id { get; set; }
        public int PH_US_Id { get; set; }
        public byte[] PH_Image { get; set; }
        public string PH_FileName { get; set; }
        public System.DateTime PH_UploadDate { get; set; }
        public bool PH_InMarket { get; set; }
        public int PH_Likes { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Favourites> Favourites { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual ICollection<Purchases> Purchases { get; set; }
        public virtual UserData UserData { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
    }
}
