//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoom3Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.UserData = new HashSet<UserData>();
        }
    
        public int ROL_Id { get; set; }
        public string ROL_Description { get; set; }
    
        public virtual ICollection<UserData> UserData { get; set; }
    }
}
